// react/app-react/src/components/cronometro/Cronometro.jsx
import './Cronometro.css';
import { Fragment , useState } from 'react';
import { useEffect } from 'react';

//El nombre de la función es el nombre de la ETIQUETA HTML del componente
export default function Cronometro (){

    const  [diferencia, setDiferencia] = useState(0);
    const  [centesima, setCentesima]   = useState(0);
    const  [segundo, setSegundo]       = useState(0);
    const  [minuto, setMinuto]         = useState(0);
    const  [hora, setHora]             = useState(0);
    // const  [interval, setInterval]     = useState();

    const iniciarIntervalo = () => {
        let empiezaCrono = new Date().getTime();
        useEffect( () =>{

            const interval = setInterval(()=>{
                console.log('Intervalo');
                setDiferencia((new Date().getTime()) - empiezaCrono);
                console.log(diferencia);
    
                setCentesima(Math.trunc((diferencia/10)%100));
                setSegundo(Math.trunc((diferencia/1000)%60));
                setMinuto(Math.trunc((diferencia/60000)%60));
                setHora(Math.trunc((diferencia/(60000*60))%60));
            },10);
            return () => {
                clearInterval(interval);
              };
        }, empiezaCrono)
    }

    return(
    <Fragment>
        <div className="crono">
    <div className="tiempo">
        <div className="horas">{hora}</div>
        <span>:</span>
        <div className="minutos">{minuto}</div>
        <span>:</span>
        <div className="segundos">{segundo}</div>
        <span>:</span>
        <div className="centesimas">{centesima}</div>
    </div>
    <div className="botonera">
        <div className="boton" id="start" onClick={iniciarIntervalo}>Empezar</div>
        {/* <div className="boton" id="pause" onClick="pauseCrono()">Parar</div>
        <div className="boton disabled" id="save">Guardar</div>
        <div className="boton" id="continue" onClick="continueCrono()">Continuar</div>
        <div className="boton" id="reset" onClick="resetCrono()">Resetear</div> */}
    </div>
    <div className="tiemposGuardados"></div>
    </div>

    </Fragment>
    )

    
}

// angular/WebRutas/src/app/components/cronometro/cronometro.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cronometro',
  templateUrl: './cronometro.component.html',
  styleUrls: ['./cronometro.component.scss']
})
export class CronometroComponent implements OnInit {

  public fechaStart: Date = new Date();
  
  public diferencia:number = 0; 
  public centesima:number  = 0;
  public segundo:number    = 0;
  public minuto:number     = 0;
  public hora:number       = 0;

  public interval:NodeJS.Timer | undefined;
  
  constructor() { }

  ngOnInit(): void {
  }


  iniciarIntervalo(tiempoTranscurrido:number){
    let empiezaCrono = new Date().getTime();
    this.interval = setInterval(()=>{
        
        this.diferencia = ((new Date().getTime()+tiempoTranscurrido) - empiezaCrono);

        this.centesima  = Math.trunc((this.diferencia/10)%100);
        this.segundo    = Math.trunc((this.diferencia/1000)%60);
        this.minuto     = Math.trunc((this.diferencia/60000)%60);
        this.hora       = Math.trunc((this.diferencia/(60000*60))%60);
    },10);
  }

  pauseCrono(){
    clearInterval(this.interval);
  }

  continueCrono(){

    let tiempoTranscurrido = (this.hora*60*60*1000)+(this.minuto*60*100)+(this.segundo*1000)+(this.centesima*10);  
    
    clearInterval(this.interval);
    this.iniciarIntervalo(tiempoTranscurrido);
  }

  resetCrono(){
    clearInterval(this.interval);

    this.centesima  = 0;
    this.segundo    = 0;
    this.minuto     = 0;
    this.hora       = 0;
    
  }
}

<div class="crono">
    <div class="tiempo">
        <div class="horas">{{hora | formatTime}}</div>
        <span>:</span>
        <div class="minutos">{{minuto | formatTime}}</div>
        <span>:</span>
        <div class="segundos">{{segundo | formatTime}}</div>
        <span>:</span>
        <div class="centesimas">{{centesima | formatTime}}</div>
    </div>
    <div class="botonera">
        <div class="boton" id="start" (click)="iniciarIntervalo(0)">Empezar</div>
        <div class="boton" id="pause" (click)="pauseCrono()">Parar</div>
        <div class="boton disabled" id="save">Guardar</div>
        <div class="boton" id="continue" (click)="continueCrono()">Continuar</div>
        <div class="boton" id="reset" (click)="resetCrono()">Resetear</div>
    </div>
    <div class="tiemposGuardados"></div>
</div>
